version: '2'
services:
  app:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    volumes:
      - ./notebooks:/home/jupyteruser/work
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LC_ALL: C
      JAVA_OPTS: -Duser.language=ja -Duser.country=JP -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
